spring:
  datasource:
    url: jdbc:postgresql://192.168.1.8:5432/filemetadb
    username:
    password:

application:
  redis:
    host: 192.168.1.8
  ftp:
    host: 192.168.1.8
    port: 21
    username:
    password:
    aes-key:
